### PR TITLE
Update search_with_q_request_builder.py

### PR DESCRIPTION
**Pull request by stbrie**
* Added key to empty url_tpl_params.

* Clarified "Usage".

### CODE REVIEW

**Review by baywet — CHANGES_REQUESTED** [review]
Hi @stbrie 
Thanks for the contribution.
Unfortunately we won't be able to accept it since this part of the code is automatically generated and would be overwritten on the next weekly generation.
@samwelkanda can you log an issue in Kiota if this still hasn't been addressed by your recent changes please?

**Comment by stbrie** [comment]
Id be happy to.  I tried figuring out how kiota makes the code after I
found subsequently another typo that I could fix.  I was unable to figure
it all out.  Please point me at the right folder in kiota and I'll do my
best.

**Comment by baywet** [comment]
@stbrie thanks for proposing. I believe @samwelkanda already addressed the issue. Can you confirm?

**Comment by stbrie** [comment]
I confirm.

**Pull request closed without merging**
